version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  app:
    build: .
    init: true                  
    ports: ["8000:8000"]
    stop_signal: SIGINT       
    stop_grace_period: 30m      
